sudo: false
language: ruby

addons:
  postgresql: "9.4"

rvm:
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.1
  - 2.4.1
  - ruby-head

gemfile:
 - Gemfile
 - Gemfile.v0.12

before_install:
  - gem install bundler

before_script:
  - mysql -uroot -e "CREATE DATABASE fluentd_test"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON fluentd_test.* TO 'fluentd'@'localhost'  IDENTIFIED BY 'fluentd';  FLUSH PRIVILEGES;"

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
